/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedDashboardLayoutImport } from './routes/_authenticated/dashboard/_layout'
import { Route as AuthenticatedDashboardLayoutIndexImport } from './routes/_authenticated/dashboard/_layout/index'
import { Route as AuthenticatedDashboardLayoutClientesIndexImport } from './routes/_authenticated/dashboard/_layout/clientes/index'
import { Route as AuthenticatedDashboardLayoutClientesNuevoImport } from './routes/_authenticated/dashboard/_layout/clientes/nuevo'
import { Route as AuthenticatedDashboardLayoutClientesClientIdImport } from './routes/_authenticated/dashboard/_layout/clientes/$clientId'

// Create Virtual Routes

const AuthenticatedDashboardImport = createFileRoute(
  '/_authenticated/dashboard',
)()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDashboardLayoutRoute =
  AuthenticatedDashboardLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

const AuthenticatedDashboardLayoutIndexRoute =
  AuthenticatedDashboardLayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)

const AuthenticatedDashboardLayoutClientesIndexRoute =
  AuthenticatedDashboardLayoutClientesIndexImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)

const AuthenticatedDashboardLayoutClientesNuevoRoute =
  AuthenticatedDashboardLayoutClientesNuevoImport.update({
    id: '/clientes/nuevo',
    path: '/clientes/nuevo',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)

const AuthenticatedDashboardLayoutClientesClientIdRoute =
  AuthenticatedDashboardLayoutClientesClientIdImport.update({
    id: '/clientes/$clientId',
    path: '/clientes/$clientId',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard/_layout': {
      id: '/_authenticated/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/_layout/': {
      id: '/_authenticated/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutIndexImport
      parentRoute: typeof AuthenticatedDashboardLayoutImport
    }
    '/_authenticated/dashboard/_layout/clientes/$clientId': {
      id: '/_authenticated/dashboard/_layout/clientes/$clientId'
      path: '/clientes/$clientId'
      fullPath: '/dashboard/clientes/$clientId'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutClientesClientIdImport
      parentRoute: typeof AuthenticatedDashboardLayoutImport
    }
    '/_authenticated/dashboard/_layout/clientes/nuevo': {
      id: '/_authenticated/dashboard/_layout/clientes/nuevo'
      path: '/clientes/nuevo'
      fullPath: '/dashboard/clientes/nuevo'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutClientesNuevoImport
      parentRoute: typeof AuthenticatedDashboardLayoutImport
    }
    '/_authenticated/dashboard/_layout/clientes/': {
      id: '/_authenticated/dashboard/_layout/clientes/'
      path: '/clientes'
      fullPath: '/dashboard/clientes'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutClientesIndexImport
      parentRoute: typeof AuthenticatedDashboardLayoutImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedDashboardLayoutRouteChildren {
  AuthenticatedDashboardLayoutIndexRoute: typeof AuthenticatedDashboardLayoutIndexRoute
  AuthenticatedDashboardLayoutClientesClientIdRoute: typeof AuthenticatedDashboardLayoutClientesClientIdRoute
  AuthenticatedDashboardLayoutClientesNuevoRoute: typeof AuthenticatedDashboardLayoutClientesNuevoRoute
  AuthenticatedDashboardLayoutClientesIndexRoute: typeof AuthenticatedDashboardLayoutClientesIndexRoute
}

const AuthenticatedDashboardLayoutRouteChildren: AuthenticatedDashboardLayoutRouteChildren =
  {
    AuthenticatedDashboardLayoutIndexRoute:
      AuthenticatedDashboardLayoutIndexRoute,
    AuthenticatedDashboardLayoutClientesClientIdRoute:
      AuthenticatedDashboardLayoutClientesClientIdRoute,
    AuthenticatedDashboardLayoutClientesNuevoRoute:
      AuthenticatedDashboardLayoutClientesNuevoRoute,
    AuthenticatedDashboardLayoutClientesIndexRoute:
      AuthenticatedDashboardLayoutClientesIndexRoute,
  }

const AuthenticatedDashboardLayoutRouteWithChildren =
  AuthenticatedDashboardLayoutRoute._addFileChildren(
    AuthenticatedDashboardLayoutRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardLayoutRoute: typeof AuthenticatedDashboardLayoutRouteWithChildren
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardLayoutRoute:
      AuthenticatedDashboardLayoutRouteWithChildren,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardLayoutRouteWithChildren
  '/dashboard/': typeof AuthenticatedDashboardLayoutIndexRoute
  '/dashboard/clientes/$clientId': typeof AuthenticatedDashboardLayoutClientesClientIdRoute
  '/dashboard/clientes/nuevo': typeof AuthenticatedDashboardLayoutClientesNuevoRoute
  '/dashboard/clientes': typeof AuthenticatedDashboardLayoutClientesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardLayoutIndexRoute
  '/dashboard/clientes/$clientId': typeof AuthenticatedDashboardLayoutClientesClientIdRoute
  '/dashboard/clientes/nuevo': typeof AuthenticatedDashboardLayoutClientesNuevoRoute
  '/dashboard/clientes': typeof AuthenticatedDashboardLayoutClientesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/_layout': typeof AuthenticatedDashboardLayoutRouteWithChildren
  '/_authenticated/dashboard/_layout/': typeof AuthenticatedDashboardLayoutIndexRoute
  '/_authenticated/dashboard/_layout/clientes/$clientId': typeof AuthenticatedDashboardLayoutClientesClientIdRoute
  '/_authenticated/dashboard/_layout/clientes/nuevo': typeof AuthenticatedDashboardLayoutClientesNuevoRoute
  '/_authenticated/dashboard/_layout/clientes/': typeof AuthenticatedDashboardLayoutClientesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/clientes/$clientId'
    | '/dashboard/clientes/nuevo'
    | '/dashboard/clientes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/dashboard'
    | '/dashboard/clientes/$clientId'
    | '/dashboard/clientes/nuevo'
    | '/dashboard/clientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/_layout'
    | '/_authenticated/dashboard/_layout/'
    | '/_authenticated/dashboard/_layout/clientes/$clientId'
    | '/_authenticated/dashboard/_layout/clientes/nuevo'
    | '/_authenticated/dashboard/_layout/clientes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/dashboard"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated/dashboard",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/dashboard/_layout"
      ]
    },
    "/_authenticated/dashboard/_layout": {
      "filePath": "_authenticated/dashboard/_layout.tsx",
      "parent": "/_authenticated/dashboard",
      "children": [
        "/_authenticated/dashboard/_layout/",
        "/_authenticated/dashboard/_layout/clientes/$clientId",
        "/_authenticated/dashboard/_layout/clientes/nuevo",
        "/_authenticated/dashboard/_layout/clientes/"
      ]
    },
    "/_authenticated/dashboard/_layout/": {
      "filePath": "_authenticated/dashboard/_layout/index.tsx",
      "parent": "/_authenticated/dashboard/_layout"
    },
    "/_authenticated/dashboard/_layout/clientes/$clientId": {
      "filePath": "_authenticated/dashboard/_layout/clientes/$clientId.tsx",
      "parent": "/_authenticated/dashboard/_layout"
    },
    "/_authenticated/dashboard/_layout/clientes/nuevo": {
      "filePath": "_authenticated/dashboard/_layout/clientes/nuevo.tsx",
      "parent": "/_authenticated/dashboard/_layout"
    },
    "/_authenticated/dashboard/_layout/clientes/": {
      "filePath": "_authenticated/dashboard/_layout/clientes/index.tsx",
      "parent": "/_authenticated/dashboard/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
