/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as LoginImport } from "./routes/login";
import { Route as AuthenticatedImport } from "./routes/_authenticated";
import { Route as IndexImport } from "./routes/index";
import { Route as AuthenticatedDashboardLayoutImport } from "./routes/_authenticated/dashboard/_layout";
import { Route as AuthenticatedDashboardLayoutIndexImport } from "./routes/_authenticated/dashboard/_layout/index";
import { Route as AuthenticatedDashboardLayoutClientesImport } from "./routes/_authenticated/dashboard/_layout/clientes";

// Create Virtual Routes

const AuthenticatedDashboardImport = createFileRoute(
  "/_authenticated/dashboard",
)();

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
} as any);

const AuthenticatedRoute = AuthenticatedImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthenticatedRoute,
} as any);

const AuthenticatedDashboardLayoutRoute =
  AuthenticatedDashboardLayoutImport.update({
    id: "/_layout",
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any);

const AuthenticatedDashboardLayoutIndexRoute =
  AuthenticatedDashboardLayoutIndexImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any);

const AuthenticatedDashboardLayoutClientesRoute =
  AuthenticatedDashboardLayoutClientesImport.update({
    id: "/clientes",
    path: "/clientes",
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthenticatedImport;
      parentRoute: typeof rootRoute;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    "/_authenticated/dashboard": {
      id: "/_authenticated/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof AuthenticatedDashboardImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/dashboard/_layout": {
      id: "/_authenticated/dashboard/_layout";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof AuthenticatedDashboardLayoutImport;
      parentRoute: typeof AuthenticatedDashboardRoute;
    };
    "/_authenticated/dashboard/_layout/clientes": {
      id: "/_authenticated/dashboard/_layout/clientes";
      path: "/clientes";
      fullPath: "/dashboard/clientes";
      preLoaderRoute: typeof AuthenticatedDashboardLayoutClientesImport;
      parentRoute: typeof AuthenticatedDashboardLayoutImport;
    };
    "/_authenticated/dashboard/_layout/": {
      id: "/_authenticated/dashboard/_layout/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof AuthenticatedDashboardLayoutIndexImport;
      parentRoute: typeof AuthenticatedDashboardLayoutImport;
    };
  }
}

// Create and export the route tree

interface AuthenticatedDashboardLayoutRouteChildren {
  AuthenticatedDashboardLayoutClientesRoute: typeof AuthenticatedDashboardLayoutClientesRoute;
  AuthenticatedDashboardLayoutIndexRoute: typeof AuthenticatedDashboardLayoutIndexRoute;
}

const AuthenticatedDashboardLayoutRouteChildren: AuthenticatedDashboardLayoutRouteChildren =
  {
    AuthenticatedDashboardLayoutClientesRoute:
      AuthenticatedDashboardLayoutClientesRoute,
    AuthenticatedDashboardLayoutIndexRoute:
      AuthenticatedDashboardLayoutIndexRoute,
  };

const AuthenticatedDashboardLayoutRouteWithChildren =
  AuthenticatedDashboardLayoutRoute._addFileChildren(
    AuthenticatedDashboardLayoutRouteChildren,
  );

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardLayoutRoute: typeof AuthenticatedDashboardLayoutRouteWithChildren;
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardLayoutRoute:
      AuthenticatedDashboardLayoutRouteWithChildren,
  };

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  );

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "": typeof AuthenticatedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/dashboard": typeof AuthenticatedDashboardLayoutRouteWithChildren;
  "/dashboard/clientes": typeof AuthenticatedDashboardLayoutClientesRoute;
  "/dashboard/": typeof AuthenticatedDashboardLayoutIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "": typeof AuthenticatedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/dashboard": typeof AuthenticatedDashboardLayoutIndexRoute;
  "/dashboard/clientes": typeof AuthenticatedDashboardLayoutClientesRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/_authenticated/dashboard": typeof AuthenticatedDashboardRouteWithChildren;
  "/_authenticated/dashboard/_layout": typeof AuthenticatedDashboardLayoutRouteWithChildren;
  "/_authenticated/dashboard/_layout/clientes": typeof AuthenticatedDashboardLayoutClientesRoute;
  "/_authenticated/dashboard/_layout/": typeof AuthenticatedDashboardLayoutIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | ""
    | "/login"
    | "/dashboard"
    | "/dashboard/clientes"
    | "/dashboard/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "" | "/login" | "/dashboard" | "/dashboard/clientes";
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/login"
    | "/_authenticated/dashboard"
    | "/_authenticated/dashboard/_layout"
    | "/_authenticated/dashboard/_layout/clientes"
    | "/_authenticated/dashboard/_layout/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/dashboard"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated/dashboard",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/dashboard/_layout"
      ]
    },
    "/_authenticated/dashboard/_layout": {
      "filePath": "_authenticated/dashboard/_layout.tsx",
      "parent": "/_authenticated/dashboard",
      "children": [
        "/_authenticated/dashboard/_layout/clientes",
        "/_authenticated/dashboard/_layout/"
      ]
    },
    "/_authenticated/dashboard/_layout/clientes": {
      "filePath": "_authenticated/dashboard/_layout/clientes.tsx",
      "parent": "/_authenticated/dashboard/_layout"
    },
    "/_authenticated/dashboard/_layout/": {
      "filePath": "_authenticated/dashboard/_layout/index.tsx",
      "parent": "/_authenticated/dashboard/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
